# Generated by Django 3.2.13 on 2022-05-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='email_name'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='last_name'),
        ),
        migrations.AddField(
            model_name='user',
            name='message_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='message_name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='first_name'),
        ),
    ]
