# Generated by Django 3.2.13 on 2022-05-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email_name',
            field=models.CharField(max_length=255, verbose_name='email_name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='message_name',
            field=models.CharField(max_length=255, verbose_name='message_name'),
        ),
    ]
