# Generated by Django 3.2.13 on 2022-05-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220519_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255, verbose_name='company')),
                ('industry', models.CharField(max_length=255, verbose_name='industry')),
                ('firstname', models.CharField(max_length=255, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=255, verbose_name='lastname')),
                ('jobtitle', models.CharField(max_length=255, verbose_name='jobtitle')),
                ('email', models.CharField(max_length=255, verbose_name='email')),
                ('MM', models.CharField(max_length=255, verbose_name='MM')),
                ('DD', models.CharField(max_length=255, verbose_name='DD')),
                ('YYYY', models.CharField(max_length=255, verbose_name='YYYY')),
                ('message', models.CharField(max_length=255, verbose_name='message')),
            ],
        ),
    ]
