# Generated by Django 3.2.13 on 2022-05-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('검토완료', '검토완료'), ('검토대기', '검토대기')], default='검토대기', max_length=32, verbose_name='상태'),
        ),
    ]
