# Generated by Django 3.2.13 on 2022-06-08 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_meeting_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='DD',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='MM',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='YYYY',
        ),
    ]
